source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Dwink' do
    pod 'AFNetworking', '~> 3.0'
    
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'Parse'
    
    pod 'MBProgressHUD', '~> 0.9.2'

    pod 'AWSCore'
    pod 'AWSS3'
    
    pod 'SDWebImage', '~>3.7'
    
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Digits'
    pod 'TwitterCore'
    
    pod 'MJRefresh'
    
    pod 'Masonry'
    
    pod 'TTTAttributedLabel'
end
